/****** Object:  Table [dbo].[WidgetPrices]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[WidgetPrices](
	[RecordID] [int] IDENTITY(1,1) NOT NULL,
	[WidgetID] [int] NULL,
	[Price] [money] NULL,
	[DateValidFrom] [datetime] NULL CONSTRAINT [DF_WidgetPrices_DateValidFrom]  DEFAULT (getdate()),
	[DateValidTo] [datetime] NULL,
	[Active] [char](1) NULL CONSTRAINT [DF_WidgetPrices_Active]  DEFAULT ('N'),
 CONSTRAINT [PK_WidgetPrices] PRIMARY KEY NONCLUSTERED 
(
	[RecordID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_WidgetPrices] ON [dbo].[WidgetPrices]
(
	[WidgetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_WidgetPrices_1] ON [dbo].[WidgetPrices]
(
	[DateValidFrom] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_WidgetPrices_2] ON [dbo].[WidgetPrices]
(
	[DateValidTo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[WidgetPrices]  WITH CHECK ADD  CONSTRAINT [FK_WidgetPrices_Widgets] FOREIGN KEY([WidgetID])
REFERENCES [dbo].[Widgets] ([RecordID])
ALTER TABLE [dbo].[WidgetPrices] CHECK CONSTRAINT [FK_WidgetPrices_Widgets]
